version: 2
updates:
  # NuGet dependencies
  - package-ecosystem: "nuget"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "23:00"
  # npm dependencies - frontend
  - package-ecosystem: "npm"
    directory: "/src/frontend/csrs-portal"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "23:00"
